Write to stderr

diff --git a/.github/workflows/validate-code.yml b/.github/workflows/validate-code.yml
--- a/.github/workflows/validate-code.yml
+++ b/.github/workflows/validate-code.yml
@@ -19,7 +19,7 @@ jobs:
         run: |
           min_version=$(grep requires-python pyproject.toml | grep -Eo [0-9]+.[0-9]+)
           if [ -z $min_version ] then
-            echo "Failed to parse version from pyproject.toml"
+            printf "Failed to parse version from pyproject.toml" >&2
             exit 1
           fi
           echo "minimum=$min_version" >> $GITHUB_OUTPUT
