Error log

diff --git a/.github/workflows/validate-code.yml b/.github/workflows/validate-code.yml
--- a/.github/workflows/validate-code.yml
+++ b/.github/workflows/validate-code.yml
@@ -17,7 +17,12 @@ jobs:
       - name: Get Minimum Python Version
         id: python-version
         run: |
-          echo "minimum=$(grep requires-python pyproject.toml | grep -Eo [0-9]+.[0-9]+)" >> $GITHUB_OUTPUT
+          $min_version=$(grep requires-python pyproject.toml | grep -Eo [0-9]+.[0-9]+)
+          if [[ -z $min_version ]] then
+            echo "Failed to parse version from pyproject.toml"
+            exit 1
+          fi
+          echo "minimum=$min_version" >> $GITHUB_OUTPUT
 
       - name: Set up Python ${{ steps.python-version.outputs.minimum }}
         uses: actions/setup-python@v5
